name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: 'skommana04/terraform_mod' 
        path: 'srikanth1'

    # - name: Show current directory (pwd)
    #   run: |
    #     echo "Current directory after checkout:"
    #     pwd

    # - name: Change directory to Development
    #   run: |
    #     cd srikanth1/Development
    #     ls -l

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: |
        ls -l  # List files in the directory for debugging
        terraform init
      working-directory: srikanth1/Development

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check
      working-directory: srikanth1/Development      

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: srikanth1/Development

